#!/usr/bin/env node
/**
 * Copyright IBM Corp. 2021, 2025
 * SPDX-License-Identifier: MPL-2.0
 */

const originalFilesize = require('filesize')
const numberToWords = require('number-to-words')
const fs = require('fs')
const path = require('path')
const {
  DEFAULT_OUTPUT_MODE,
  getBuildOutputDirectory,
  getOptions,
} = require('./utils')

const MANAGED_COMMENT_TAG = '<!-- __NEXTJS_BUNDLE_ANALYSIS__ -->'
const DEFAULT_MINIMUM_TOTAL_CHANGE_THRESHOLD = 1024

/**
 * @typedef {{
 *   page: string,
 *   raw: number,
 *   gzip: number,
 *   rawDiff?: number,
 *   gzipDiff?: number,
 *   increase?: boolean
 * }} BundleEntry
 */

/**
 * @typedef {{
 *   page: BundleEntry[],
 *   global: BundleEntry | null
 * }} ThresholdBreaches
 */

/**
 * @typedef {{
 *   budget?: number,
 *   budgetPercentIncreaseRed?: number,
 *   showDetails?: boolean,
 *   buildOutputDirectory?: string,
 *   name: string,
 *   outputMode?: string,
 *   skipCommentIfEmpty?: boolean,
 *   minimumChangeThreshold?: number,
 *   minimumTotalChangeThreshold?: number,
 *   alwaysShowGzipDiff?: boolean
 * }} CompareOptions
 */

/**
 * @typedef {{
 *   packageName: string,
 *   outputMode: string,
 *   managedCommentTag: string,
 *   legacyManagedCommentTag: string,
 *   checkName: string,
 *   checkTitle: string,
 *   checkConclusion: 'success' | 'neutral',
 *   missingBase: boolean,
 *   hasNoChanges: boolean,
 *   thresholdBreaches: ThresholdBreaches,
 *   report: string,
 *   commentBody: string
 * }} CompareResult
 */

/**
 * @typedef {{
 *   options: CompareOptions,
 *   budget?: number,
 *   budgetPercentIncreaseRed: number,
 *   showDetails: boolean,
 *   packageName: string,
 *   outputMode: string,
 *   skipCommentIfEmpty: boolean,
 *   minimumChangeThreshold: number,
 *   minimumTotalChangeThreshold: number,
 *   alwaysShowGzipDiff: boolean,
 *   managedCommentTag: string,
 *   legacyManagedCommentTag: string,
 *   checkName: string
 * }} CompareContext
 */

/**
 * Override default filesize options to display a non-breakable space as a spacer.
 *
 * @param {number} bytes
 * @param {Parameters<typeof originalFilesize>[1]} [options]
 * @returns {string}
 */
function filesize(bytes, options) {
  return originalFilesize(bytes, {
    spacer: ' ',
    ...options,
  })
}

/**
 * @param {CompareOptions} options
 * @returns {CompareContext}
 */
function createCompareContext(options) {
  const packageName = options.name

  return {
    options,
    budget: options.budget,
    budgetPercentIncreaseRed: options.budgetPercentIncreaseRed || 20,
    showDetails: options.showDetails === undefined ? true : options.showDetails,
    packageName,
    outputMode: options.outputMode || DEFAULT_OUTPUT_MODE,
    skipCommentIfEmpty: Boolean(options.skipCommentIfEmpty),
    minimumChangeThreshold: options.minimumChangeThreshold || 0,
    minimumTotalChangeThreshold:
      options.minimumTotalChangeThreshold === undefined
        ? DEFAULT_MINIMUM_TOTAL_CHANGE_THRESHOLD
        : options.minimumTotalChangeThreshold,
    alwaysShowGzipDiff: Boolean(options.alwaysShowGzipDiff),
    managedCommentTag: MANAGED_COMMENT_TAG,
    legacyManagedCommentTag: `<!-- __NEXTJS_BUNDLE_${packageName} -->`,
    checkName: packageName
      ? `nextjs-bundle-analysis / ${packageName}`
      : 'Next.js Bundle Analysis',
  }
}

/**
 * @param {CompareContext} context
 * @returns {string}
 */
function createHeader(context) {
  return `## 📦 Next.js Bundle Analysis for ${context.packageName}

This analysis was generated by the [Next.js Bundle Analysis action](https://github.com/hashicorp/nextjs-bundle-analysis). 🤖

`
}

/**
 * @param {CompareContext} context
 * @returns {CompareResult}
 */
function createMissingBaseResult(context) {
  const report = `${createHeader(context)}No base bundle artifact was found for this pull request yet, so this run could not compare changes against the base branch.

Push the default branch bundle artifact once and future PR runs will include a full comparison.`

  return {
    packageName: context.packageName,
    outputMode: context.outputMode,
    managedCommentTag: context.managedCommentTag,
    legacyManagedCommentTag: context.legacyManagedCommentTag,
    checkName: context.checkName,
    checkTitle: 'Base bundle artifact missing',
    checkConclusion: 'neutral',
    missingBase: true,
    hasNoChanges: false,
    thresholdBreaches: {
      page: [],
      global: null,
    },
    report: report.trim(),
    commentBody: getCommentBody(context, {
      report,
      hasNoChanges: false,
      thresholdBreaches: {
        page: [],
        global: null,
      },
      missingBase: true,
    }),
  }
}

/**
 * @param {CompareContext} context
 * @param {string} reason
 * @returns {CompareResult}
 */
function createNeutralResult(context, reason) {
  const report = `${createHeader(context)}${reason}`

  return {
    packageName: context.packageName,
    outputMode: context.outputMode,
    managedCommentTag: context.managedCommentTag,
    legacyManagedCommentTag: context.legacyManagedCommentTag,
    checkName: context.checkName,
    checkTitle: 'Bundle analysis unavailable',
    checkConclusion: 'neutral',
    missingBase: false,
    hasNoChanges: false,
    thresholdBreaches: {
      page: [],
      global: null,
    },
    report: report.trim(),
    commentBody: '',
  }
}

/**
 * @param {CompareContext} context
 * @param {Record<string, BundleEntry>} currentBundleData
 * @param {Record<string, BundleEntry>} baseBundleData
 * @returns {CompareResult}
 */
function analyzeBundleDiff(context, currentBundleData, baseBundleData) {
  const currentBundle = { ...currentBundleData }
  const baseBundle = { ...baseBundleData }

  let output = createHeader(context)

  const globalBundleCurrent = currentBundle.__global
  const globalBundleBase = baseBundle.__global

  if (!globalBundleCurrent || !globalBundleBase) {
    return createNeutralResult(
      context,
      'The bundle analysis artifact format is missing the global bundle metadata required for comparison.'
    )
  }

  delete currentBundle.__global
  delete baseBundle.__global

  /** @type {BundleEntry | false} */
  let globalBundleChanges = false
  const globalGzipDiff = globalBundleCurrent.gzip - globalBundleBase.gzip

  if (
    globalGzipDiff !== 0 &&
    Math.abs(globalGzipDiff) > context.minimumTotalChangeThreshold
  ) {
    globalBundleChanges = {
      page: 'global',
      raw: globalBundleCurrent.raw,
      gzip: globalBundleCurrent.gzip,
      gzipDiff: globalGzipDiff,
      increase: globalGzipDiff > 0,
    }
  }

  /** @type {BundleEntry[]} */
  const changedPages = []
  /** @type {BundleEntry[]} */
  const newPages = []

  for (const [page, currentStats] of Object.entries(currentBundle)) {
    const baseStats = baseBundle[page]

    if (!baseStats) {
      newPages.push({ page, ...currentStats })
      continue
    }

    if (currentStats.gzip === baseStats.gzip) continue

    const rawDiff = currentStats.raw - baseStats.raw
    const gzipDiff = currentStats.gzip - baseStats.gzip

    if (Math.abs(gzipDiff) > context.minimumChangeThreshold) {
      changedPages.push({
        page,
        ...currentStats,
        rawDiff,
        gzipDiff,
        increase: gzipDiff > 0,
      })
    }
  }

  if (globalBundleChanges) {
    output += `### ${
      globalBundleChanges.increase ? '⚠️' : '🎉'
    }  Global Bundle Size ${
      globalBundleChanges.increase ? 'Increased' : 'Decreased'
    }
  
`
    output += markdownTable(context, globalBundleChanges)

    if (context.showDetails) {
      output += `\n<details>
<summary>Details</summary>
<p>The <strong>global bundle</strong> is the javascript bundle that loads alongside every page. It is in its own category because its impact is much higher - an increase to its size means that every page on your website loads slower, and a decrease means every page loads faster.</p>
<p>Any third party scripts you have added directly to your app using the <code>&lt;script&gt;</code> tag are not accounted for in this analysis</p>
<p>If you want further insight into what is behind the changes, give <a href='https://www.npmjs.com/package/@next/bundle-analyzer'>@next/bundle-analyzer</a> a try!</p>
</details>\n\n`
    }
  }

  if (newPages.length) {
    const plural = newPages.length > 1 ? 's' : ''
    output += `### New Page${plural} Added
  
The following page${plural} ${
      plural === 's' ? 'were' : 'was'
    } added to the bundle from the code in this PR:

`
    output += markdownTable(context, newPages, globalBundleCurrent) + '\n'
  }

  if (changedPages.length) {
    const plural = changedPages.length > 1 ? 's' : ''
    output += `### ${titleCase(
      numberToWords.toWords(changedPages.length)
    )} Page${plural} Changed Size
  
The following page${plural} changed size from the code in this PR compared to its base branch:

`
    output += markdownTable(
      context,
      changedPages,
      globalBundleCurrent,
      globalBundleBase
    )

    if (context.showDetails) {
      output += `\n<details>
<summary>Details</summary>
<p>Only the gzipped size is provided here based on <a href='https://twitter.com/slightlylate/status/1412851269211811845'>an expert tip</a>.</p>
<p><strong>First Load</strong> is the size of the global bundle plus the bundle for the individual page. If a user were to show up to your website and land on a given page, the first load size represents the amount of javascript that user would need to download. If <code>next/link</code> is used, subsequent page loads would only need to download that page's bundle (the number in the "Size" column), since the global bundle has already been downloaded.</p>
<p>Any third party scripts you have added directly to your app using the <code>&lt;script&gt;</code> tag are not accounted for in this analysis</p>
${
  context.budget && globalBundleCurrent
    ? `<p>The "Budget %" column shows what percentage of your performance budget the <strong>First Load</strong> total takes up. For example, if your budget was 100kb, and a given page's first load size was 10kb, it would be 10% of your budget. You can also see how much this has increased or decreased compared to the base branch of your PR. If this percentage has increased by ${context.budgetPercentIncreaseRed}% or more, there will be a red status indicator applied, indicating that special attention should be given to this. If you see "+/- <0.01%" it means that there was a change in bundle size, but it is a trivial enough amount that it can be ignored.</p>`
    : `<p>Next to the size is how much the size has increased or decreased compared with the base branch of this PR. If this percentage has increased by ${context.budgetPercentIncreaseRed}% or more, there will be a red status indicator applied, indicating that special attention should be given to this.</p>`
}
</details>\n`
    }
  }

  const hasNoChanges =
    !newPages.length && !changedPages.length && !globalBundleChanges

  if (hasNoChanges) {
    output += 'This PR introduced no changes to the JavaScript bundle! 🙌'
  }

  const thresholdBreaches = getThresholdBreaches(context, changedPages, globalBundleChanges)
  const commentBody = getCommentBody(context, {
    report: output,
    hasNoChanges,
    thresholdBreaches,
  })

  return {
    packageName: context.packageName,
    outputMode: context.outputMode,
    managedCommentTag: context.managedCommentTag,
    legacyManagedCommentTag: context.legacyManagedCommentTag,
    checkName: context.checkName,
    checkTitle: hasNoChanges
      ? 'No bundle changes'
      : 'Bundle analysis completed',
    checkConclusion: 'success',
    missingBase: false,
    hasNoChanges,
    thresholdBreaches,
    report: output.trim(),
    commentBody,
  }
}

/**
 * @param {CompareContext} context
 * @param {{
 *   report: string,
 *   hasNoChanges: boolean,
 *   thresholdBreaches: ThresholdBreaches,
 *   missingBase?: boolean
 * }} params
 * @returns {string}
 */
function getCommentBody(
  context,
  { report, hasNoChanges, thresholdBreaches, missingBase = false }
) {
  if (context.outputMode === 'comment' || context.outputMode === 'both') {
    if (hasNoChanges && context.skipCommentIfEmpty) return ''
    return `${report.trim()}\n\n${renderManagedTags(context)}`
  }

  if (missingBase || !hasThresholdComment(thresholdBreaches)) {
    return ''
  }

  return `${renderThresholdCommentSummary(context, thresholdBreaches)}

See the \`${context.checkName}\` check for the full report.

${renderManagedTags(context)}`.trim()
}

/**
 * @param {CompareContext} context
 * @returns {string}
 */
function renderManagedTags(context) {
  return `${context.legacyManagedCommentTag}\n${context.managedCommentTag}`
}

/**
 * @param {CompareContext} context
 * @param {BundleEntry[]} changedPages
 * @param {BundleEntry | false} globalBundleChanges
 * @returns {ThresholdBreaches}
 */
function getThresholdBreaches(context, changedPages, globalBundleChanges) {
  return {
    page: changedPages.filter(
      (page) => Boolean(page.increase) && page.gzipDiff > context.minimumChangeThreshold
    ),
    global:
      globalBundleChanges &&
      globalBundleChanges.increase &&
      globalBundleChanges.gzipDiff > context.minimumTotalChangeThreshold
        ? globalBundleChanges
        : null,
  }
}

/**
 * @param {ThresholdBreaches} thresholdBreaches
 * @returns {boolean}
 */
function hasThresholdComment(thresholdBreaches) {
  return Boolean(thresholdBreaches.global || thresholdBreaches.page.length)
}

/**
 * @param {CompareContext} context
 * @param {ThresholdBreaches} thresholdBreaches
 * @returns {string}
 */
function renderThresholdCommentSummary(context, thresholdBreaches) {
  const lines = ['## ⚠️ Bundle size regression detected', '']

  if (thresholdBreaches.global) {
    lines.push(
      `Global bundle increased by \`${filesize(
        thresholdBreaches.global.gzipDiff
      )}\`, exceeding the \`${filesize(
        context.minimumTotalChangeThreshold
      )}\` threshold.`
    )
  }

  if (thresholdBreaches.page.length) {
    const pageList = thresholdBreaches.page
      .slice(0, 5)
      .map((page) => `\`${page.page}\` (+${filesize(page.gzipDiff || 0)})`)
      .join(', ')
    const suffix =
      thresholdBreaches.page.length > 5
        ? `, and ${thresholdBreaches.page.length - 5} more`
        : ''

    lines.push(
      `${thresholdBreaches.page.length} page bundle ${
        thresholdBreaches.page.length === 1 ? 'increase' : 'increases'
      } exceeded the \`${filesize(context.minimumChangeThreshold)}\` threshold: ${pageList}${suffix}.`
    )
  }

  return lines.join('\n')
}

/**
 * @param {CompareContext} context
 * @param {BundleEntry | BundleEntry[]} dataInput
 * @param {BundleEntry} [globalBundleCurrent]
 * @param {BundleEntry} [globalBundleBase]
 * @returns {string}
 */
function markdownTable(context, dataInput, globalBundleCurrent, globalBundleBase) {
  const data = [].concat(dataInput)
  const showBudget = Boolean(globalBundleCurrent && context.budget)
  const showBudgetDiff = Boolean(context.budget && globalBundleBase)

  return `Page | Size (compressed) | ${
    globalBundleCurrent ? 'First Load |' : ''
  }${showBudget ? ` % of Budget (\`${filesize(context.budget)}\`) |` : ''}
|---|---|${globalBundleCurrent ? '---|' : ''}${showBudget ? '---|' : ''}
${data
  .map((entry) => renderMarkdownRow(context, entry, {
    showBudget,
    showBudgetDiff,
    globalBundleCurrent,
    globalBundleBase,
  }))
  .join('')}`
}

/**
 * @param {CompareContext} context
 * @param {BundleEntry} entry
 * @param {{
 *   showBudget: boolean,
 *   showBudgetDiff: boolean,
 *   globalBundleCurrent?: BundleEntry,
 *   globalBundleBase?: BundleEntry
 * }} options
 * @returns {string}
 */
function renderMarkdownRow(
  context,
  entry,
  { showBudget, showBudgetDiff, globalBundleCurrent, globalBundleBase }
) {
  const firstLoadSize = globalBundleCurrent
    ? entry.gzip + globalBundleCurrent.gzip
    : 0

  const budgetPercentage =
    showBudget && context.budget
      ? ((firstLoadSize / context.budget) * 100).toFixed(2)
      : 0

  const previousFirstLoadSize =
    globalBundleBase && typeof entry.gzipDiff === 'number'
      ? globalBundleBase.gzip + (entry.gzip - entry.gzipDiff)
      : 0

  const previousBudgetPercentage =
    showBudget && previousFirstLoadSize && context.budget
      ? ((previousFirstLoadSize / context.budget) * 100).toFixed(2)
      : 0

  const budgetChange = previousBudgetPercentage
    ? (Number.parseFloat(budgetPercentage) - Number.parseFloat(previousBudgetPercentage)).toFixed(2)
    : 0

  return (
    `| \`${entry.page}\`` +
    renderSize(context, entry, showBudgetDiff) +
    renderFirstLoad(globalBundleCurrent, firstLoadSize) +
    renderBudgetPercentage(
      context,
      showBudget,
      budgetPercentage,
      previousBudgetPercentage,
      budgetChange
    ) +
    ' |\n'
  )
}

/**
 * @param {BundleEntry | undefined} globalBundleCurrent
 * @param {number} firstLoadSize
 * @returns {string}
 */
function renderFirstLoad(globalBundleCurrent, firstLoadSize) {
  if (!globalBundleCurrent) return ''
  return ` | ${filesize(firstLoadSize)}`
}

/**
 * @param {CompareContext} context
 * @param {BundleEntry} entry
 * @param {boolean} showBudgetDiff
 * @returns {string}
 */
function renderSize(context, entry, showBudgetDiff) {
  const gzipDiff = entry.gzipDiff
  const baseGzip =
    typeof gzipDiff === 'number' ? entry.gzip - gzipDiff : entry.gzip
  const percentChange =
    gzipDiff && baseGzip !== 0
      ? (gzipDiff / baseGzip) * 100
      : 0

  return ` | \`${filesize(entry.gzip)}\`${
    gzipDiff && (context.alwaysShowGzipDiff || !showBudgetDiff)
      ? ` _(${renderStatusIndicator(context, percentChange)}${filesize(gzipDiff)})_`
      : ''
  }`
}

/**
 * @param {CompareContext} context
 * @param {boolean} showBudget
 * @param {number | string} budgetPercentage
 * @param {number | string} previousBudgetPercentage
 * @param {number | string} budgetChange
 * @returns {string}
 */
function renderBudgetPercentage(
  context,
  showBudget,
  budgetPercentage,
  previousBudgetPercentage,
  budgetChange
) {
  if (!showBudget) return ''

  const numericBudgetChange = Number.parseFloat(String(budgetChange))
  const budgetChangeText = ` _(${renderStatusIndicator(context, numericBudgetChange)}${
    numericBudgetChange < 0.01 && numericBudgetChange > -0.01
      ? '+/- <0.01%'
      : `${budgetChange}%`
  })_`

  return ` | ${budgetPercentage}%${
    previousBudgetPercentage ? budgetChangeText : ''
  }`
}

/**
 * @param {CompareContext} context
 * @param {number} percentageChange
 * @returns {string}
 */
function renderStatusIndicator(context, percentageChange) {
  if (!Number.isFinite(percentageChange)) return ''
  if (
    percentageChange > 0 &&
    percentageChange < context.budgetPercentIncreaseRed
  ) {
    return '🟡 +'
  }
  if (percentageChange >= context.budgetPercentIncreaseRed) {
    return '🔴 +'
  }
  if (percentageChange < 0.01 && percentageChange > -0.01) {
    return ''
  }
  return '🟢 '
}

/**
 * @param {string} str
 * @returns {string}
 */
function titleCase(str) {
  return str.replace(/\w\S*/g, (txt) => {
    return txt.charAt(0).toUpperCase() + txt.slice(1).toLowerCase()
  })
}

/**
 * @param {string} filePath
 * @returns {Record<string, BundleEntry> | null}
 */
function readBundleIfExists(filePath) {
  if (!fs.existsSync(filePath)) return null
  return JSON.parse(fs.readFileSync(filePath, 'utf8'))
}

/**
 * @param {CompareContext} context
 * @param {string} outputRoot
 * @returns {CompareResult}
 */
function runCompare(context, outputRoot) {
  const currentBundlePath = path.join(outputRoot, '__bundle_analysis.json')
  const baseBundlePath = path.join(outputRoot, 'base/bundle/__bundle_analysis.json')
  const currentBundle = readBundleIfExists(currentBundlePath)

  if (!currentBundle) {
    return createNeutralResult(
      context,
      'No current bundle artifact was found for this run, so bundle analysis could not be generated.'
    )
  }

  const baseBundle = readBundleIfExists(baseBundlePath)
  if (!baseBundle) {
    return createMissingBaseResult(context)
  }

  return analyzeBundleDiff(context, currentBundle, baseBundle)
}

/**
 * @returns {void}
 */
function main() {
  const options = /** @type {CompareOptions} */ (getOptions())
  const context = createCompareContext(options)
  const outputRoot = path.join(
    process.cwd(),
    getBuildOutputDirectory(options),
    'analyze'
  )
  const commentOutputPath = path.join(outputRoot, '__bundle_analysis_comment.txt')
  const metadataOutputPath = path.join(outputRoot, '__bundle_analysis_output.json')

  const result = runCompare(context, outputRoot)

  console.log(result.report)
  fs.writeFileSync(commentOutputPath, (result.commentBody || '').trim())
  fs.writeFileSync(metadataOutputPath, JSON.stringify(result, null, 2))
}

if (require.main === module) {
  main()
}

module.exports = {
  DEFAULT_MINIMUM_TOTAL_CHANGE_THRESHOLD,
  MANAGED_COMMENT_TAG,
  analyzeBundleDiff,
  createCompareContext,
  markdownTable,
  renderStatusIndicator,
  runCompare,
}
